name: Cy tests for Status Page

# The type of runner that the job will run on
on:
  schedule:
    - cron: "0 6 * * 1-5"

  push:
    branches:
      - 'main'

  workflow_dispatch:

jobs:

  #test_schedule:
  regression-test-and-reports:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."

      - name: CI BUILD
        uses: actions/checkout@v3

      - name: Write the cypress.env.json file ðŸ“
        # use quotes around the secret, as its value
        # is simply inserted as a string into the command
        run: |
          echo '${{ secrets.CYPRESS_ENV_CI }}' > cypress.env.json

      - name: npm install
        run: npm install && npm install cypress@10.9.0 cypress-cucumber-preprocessor

      - name: CI TESTING
        uses: cypress-io/github-action@v3
        continue-on-error: true
        timeout-minutes: 300
        with:
          browser: chrome
